sudo: required

services:
    - docker

notifications:
    email: false

before_install:
    # Create .splunkrc file with default credentials
    - echo host=localhost >> $HOME/.splunkrc
    - echo username=admin >> $HOME/.splunkrc
    - echo password=changed! >> $HOME/.splunkrc
    # Set SPLUNK_HOME
    - export SPLUNK_HOME="/opt/splunk"
    # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
    - sudo iptables -N DOCKER || true
    # Start docker-compose in detached mode
    - docker-compose up -d
    # Health Check (3 minutes)
    - for i in `seq 0 180`; do if docker exec -it splunk /sbin/checkstate.sh &> /dev/null; then break; fi; echo $i; sleep 1; done

language: node_js
node_js:
    - "10.0"
    - "4.2"
    - "0.12"

env:
    - SPLUNK_VERSION=8.0
    - SPLUNK_VERSION=8.1

before_script:
    node sdkdo hint

# Test script, should return non 0 exit status if a test fails
script:
    node sdkdo tests
